# -*- coding: utf-8 -*-
"""ex_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RN6ELQJl10WpWGMkSh10Lz0p-E1suSNB
"""

def ConquestCampaign(N:int,M:int,L:int,batalion:[int])->int:

  enemy_terra=[[0]*M for _ in range(N) ]
  batalion=[i-1 for i in batalion]

  i=0
  bat_mat=[]
  while i<len(batalion):
    bat_mat.append(batalion[i:i+2])
    i+=2
  
  for indexN, item in enumerate(enemy_terra):
    for indexM,el in enumerate(item):
      lop=[indexN,indexM]
      if lop in bat_mat:
        
        enemy_terra[indexN][indexM]=1

  days=0


  

  
  for indexM,el in enumerate(item):
    
    if enemy_terra[indexN][indexM]==1 and (indexN-1)>=0 and (indexN-1)<=N-1 and (indexM)>=0 and (indexM) <=M-1 and enemy_terra[indexN-1][indexM]==0:
      enemy_terra[indexN-1][indexM]=1

    if enemy_terra[indexN][indexM]==1 and (indexN +1)>=0 and (indexN + 1)<=N-1 and (indexM)>=0 and (indexM) <=M-1 and enemy_terra[indexN+1][indexM]==0:
      enemy_terra[indexN + 1][indexM]=1

    if enemy_terra[indexN][indexM]==1 and (indexN)>=0 and (indexN)<=N-1 and (indexM-1)>=0 and (indexM-1) <=M-1 and enemy_terra[indexN][indexM-1]==0:
      enemy_terra[indexN][indexM-1]=1

    if enemy_terra[indexN][indexM]==1 and (indexN)>=0 and (indexN)<=N-1 and (indexM+1)>=0 and (indexM +1 ) <= 3 and enemy_terra[indexN][indexM+1]==0:
      enemy_terra[indexN][indexM+1]=1
      
    days+=1
  return days