# -*- coding: utf-8 -*-
"""task_14fin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ey7T2XZ7wlzeHMMqyi0WF6wP_S3-CknA
"""

def Unmanned(L,N,track):

  sost={}
  sost1={}

  for i in track:
    sost[i[0]]=i[1:]
    sost1[i[0]]=i[1:]

  time=0


  for i in range (1,L+1):
    
    
    time+=1
  
  
  
    for key, value in sost1.items():


      if sost1[key][0]==0 and sost1[key][1]==0:
        sost1[key]=sost[key]



      if sost1[key][0]>0:
        sost1[key][0]-=1
      



      
      if sost1[key][0]==0 and sost1[key][1]>0:
        sost1[key][1]-=1

      if i==key and sost1[key][0]>0:
        time+= sost1[key][0]+1
        
        

    

  return time
