# -*- coding: utf-8 -*-
"""task_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wqqygTPxYpK_OGZyCeP65Hquq8cv2xkZ
"""

def SynchronizingTables(N,ids,salary):
  sort_ids=sorted(ids)
  sort_salary=sorted(salary)
  dict_id_sailary={i:j for i,j in zip(sort_ids,sort_salary)}
  real_salary=[dict_id_sailary[x]for x in ids]
  
  
      
  return real_salary