# -*- coding: utf-8 -*-
"""task_12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jdn3P-CJ_4UOneDZ_IKiEyvqyyIcIvcz
"""

def MassVote(N,Votes):

  votes_per=[(sum(Votes)/100)* i for i in Votes]
  barrier=0.5*sum(Votes)

  viner=max(votes_per)

  Viner_list=[i for i, j in enumerate(votes_per) if j == viner]

  if len(Viner_list)>1:
    result='no winner'

  else:

    if votes_per[Viner_list[0]]>barrier:
      result='majority winner '+ (str(Viner_list[0]+1))

    else:
      result='minority winner '+ (str(Viner_list[0]+1))

  return result
