# -*- coding: utf-8 -*-
"""task6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fcoms28ggU9n1lUtCvHrt7s77OtEXh5q
"""

def PatternUnlock(N,hits):
  distance=round(0,5)
  neib_diff=round(2**(1/2),5)
  for numbr in range(1,N) :
    dist=(hits[numbr]-hits[numbr-1])
    if dist==1:
      distance+=1
    
    else:
      distance+=neib_diff
  
  replace=".0"
  str_distance=str(distance)
  for char in replace:
    str_distance = str_distance.replace(char, "")
  

    
  str_distance=str(distance)

  return str_distance