# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eOGuk0tnC-dXKkmNj8EIuiJRoZdR47gp
"""

def MadMax(N,Tele):
  STele=sorted(Tele)
  half=int(N/2)
  return STele[:half] + sorted(STele[half:],reverse=True)