# -*- coding: utf-8 -*-
"""task_7_fin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C8ELscDSEUmrjWyyNibaS9wxQrPPAnGJ
"""

def WordSearch(lent,s,subs ):

  splited_string=s.split()

  new_state_list=[]

  for index, word in enumerate(splited_string):
    if len(word)>lent:

      parts = [word[i:i+lent] for i in range(0, len(word), lent)]
      for part in parts:
        new_state_list.append(part)
         
        
       
    
    else:
        new_state_list.append(splited_string[index])


  for index, word in enumerate(new_state_list):
    if  index>0 and len(new_state_list[index-1]+' '+ word)<(lent+1): 
          new_state_list[index]= new_state_list[index-1]+' '+ word
          del new_state_list[index-1]


  digits=[]

  for word in new_state_list:
    if subs  in word.split():
      digits.append(1)
    else:
      digits.append(0)

  return digits