# -*- coding: utf-8 -*-
"""task_8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11r3xD5okAkgL5ETC_xoXZeLEdpmfnxfK
"""

def SumOfThe(N,data):
  for i in data:
    if i==sum(data)-i:
      number=i
  return number