# -*- coding: utf-8 -*-
"""task_13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18rTW-Bbt46f5nZ-e0zDuzVC0NKQ_l5DU
"""

def UFO(N,data,octal):
  if octal==True:
    base=8
  else:
    base=16
  
  revers=[]
  for digit in data:
    value=str(digit)
    value=value[::-1]
    revers.append(value)

  decod=[]

  for number in revers:
    new=sum([int(i)*(base**index) for index,i in enumerate(number)])
    decod.append(new)

  return decod